notifications:
  email: false

language: python

cache: pip

python:
  - 2.7

matrix:
  fast_finish: true

before_install:
  - travis_retry pip install --upgrade pip setuptools

install:
  - travis_retry pip install -r requirements.txt

script:
  - cpplint --quiet --recursive src
